### ISSUE TITLE
Firefox "forgets" Sync account

### ISSUE THREAD

**Issue by stdll** [owncloud/mozilla_sync#112]
I have the problem that Firefox periodically forgets about my Sync account.

I can create a sync account just fine with my owncloud instance and after synchronization, the sync app tells me:

> Synchronisation-Status
> Letzte Synchronisation    2014-03-25 06:14:30 UTC
> Größe der gespeicherten Daten    296 kB (unlimited quota)
> Anzahl der synchronisierten Geräte    1 

Firefox also tells me that everything works fine. However, after several system reboots, Firefox seems to have forgotten about my Sync account. The only option I have is to create another account. However, when I enter my owncloud credentials again, it tells me the account is already in use:
![mozilla sync](https://cloud.githubusercontent.com/assets/894220/2535248/f1603af2-b58b-11e3-8870-f9fe6b0453f0.png)

I'm using:
- Firefox 28
- owncloud 6.0.2
- mozilla_sync 1.4

Does anybody know if that's an error on my side or a bug?
Thanks in advance!
r3nj1

**Comment by gene-pavlovsky** [comment]
Hey guys, it's very nice you are both German, but for sake of sharing knowledge it would be nice if you kept your conversation here in English. Other people with same problem could use your help!

**Comment by FlorianSteller** [comment]
@mistabob thank you! Seems to work fine (for Firefox and the Developer Edition). I will test this the next days on more devices and on Mac, too.

@gene-pavlovsky You are right. I`m also from Germany, but we should think global :)

@anyone: Run KeePass before starting Firefox should be a workaround
