### ISSUE TITLE
Installation guide out of date

### ISSUE THREAD

**Issue by mr-july** [owncloud/mozilla_sync#127]
The documentation [Changing your Mozilla Sync installation](https://github.com/owncloud/mozilla_sync/blob/master/INSTALL.md) is not usable anymore. The actual version of Firefox (34.0) have no user interface for custom server specification, thus it is not possible to configure the sync. Probably the parameters in about:config should be used to setup the configuration. Could anybody figure out and document how to setup the sync in modern Firefox?

**Comment by beyerservice** [comment]
sorry for the delay :-)
