### ISSUE TITLE
Can i show my bookmark sync on owncloud interfarce ?

### ISSUE THREAD

**Issue by ychoucha** [owncloud/mozilla_sync#136]
Hello,

now i have syncing my firefoxw 37 with owncloud that's cool !!

but on owncloud interface i can see where is my data is please ?
![fichiers - owncloud - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/7044817/bc575c4c-ddf7-11e4-8afa-a953eee90d90.jpg)

**Comment by ogasser** [comment]
No, this is not possible. See the related issue #40.
