### ISSUE TITLE
FF37 no custom server

### ISSUE THREAD

**Issue by gerroon** [owncloud/mozilla_sync#138]
Hi

I cant seem to be able to see a custom server setting on my FF sync page (based on the install md). Is v37 supported?

**Comment by freibadschwimmer** [comment]
Firefox removed the option for adding your own server from the GUI in the latest versions, you need to fiddle around in the about:config now to get the sync working:
Add a new string: 'services.sync.username' and give any name, restart FF, and try to go into the GUI again, it show then the possibility to connect your own sync server.
Check here for more information on this issue: https://apps.owncloud.com/content/show.php/Mozilla+Sync?content=161793

**Comment by gerroon** [comment]
@freibadschwimmer 

Thank you.

**Comment by gerroon** [comment]
Hi
'
I just want to confirm that following the stesp in the docs work for FF37.

Btw can I use single user name across multiple computers to sync between devices? Or do I have to use the pairing thing ? Sorry to ask here I just do not know how this handled by going through OC.

Anyway great addon, thanks for the hard work.
