### ISSUE TITLE
Guide for setting up on Android

### ISSUE THREAD

**Issue by SudoHenk** [owncloud/mozilla_sync#145]
Hi, I have trouble setting up this custom Sync for android Mobile. Apperantly you can use https://addons.mozilla.org/nl/android/addon/fxa-custom-server-addon/ to set custom URL's, but do these both need to be the `.../remote.php/mozilla_sync/` URL?

And how can I troubleshoot since it will only tell me there "was a problem" meanwhile its working fine on my Desktop.

Also, is SNI a problem that requires me to buy a new ip, or is this only a problem with self signed certs?

**Comment by RealRancor** [comment]
The mozilla_sync is currently not compatible with the newer firefox versions providing this fxa accounts / sync 1.5 as already discussed here: https://github.com/owncloud/mozilla_sync/issues/33
